//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimalCut
    {
        public PrimalCut()
        {
            this.CutNames = new HashSet<CutName>();
        }
    
        public int PrimalCutId { get; set; }
        public string PrimalCutName { get; set; }
        public int AnimalId { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual ICollection<CutName> CutNames { get; set; }
    }
}
