//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeatMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookType
    {
        public CookType()
        {
            this.CookCuts = new HashSet<CookCut>();
        }
    
        public int CookId { get; set; }
        public string CookType1 { get; set; }
    
        public virtual ICollection<CookCut> CookCuts { get; set; }
    }
}
