//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeatMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutName
    {
        public CutName()
        {
            this.AltNames = new HashSet<AltName>();
            this.CookCuts = new HashSet<CookCut>();
        }
    
        public int CutId { get; set; }
        public string CutName1 { get; set; }
        public int PrimalCutId { get; set; }
    
        public virtual ICollection<AltName> AltNames { get; set; }
        public virtual ICollection<CookCut> CookCuts { get; set; }
        public virtual PrimalCut PrimalCut { get; set; }
    }
}
