USE [FinalProjectDB]
GO

/****** Object:  Table [dbo].[CookType]    Script Date: 8/4/2014 3:41:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CookType](
	[CookId] [int] IDENTITY(1,1) NOT NULL,
	[CookType] [varchar](50) NULL,
 CONSTRAINT [PK_CookType] PRIMARY KEY CLUSTERED 
(
	[CookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

